---
galaxy_info:
  author: Maria Vincent
  description: An Ansible role for installing Stucco UI on Ubuntu.
  company: Oak Ridge National Laboratory
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Debian
    versions:
    - 7
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies:
  - { role: stucco.common }
  - { role: jgoodall.maven3 }
  - { role: ansible-role.nodejs }
