---

- name: make sure rabbitmq-server is running
  service: name=rabbitmq-server state=started

- name: download collectors repo
  git: repo=https://github.com/stucco/collectors.git dest={{ stucco_collector_dir }}
  become: true
  become_user: stucco

- name: copy scheduler config
  template: src=collectors.yml dest={{ stucco_collector_config }}
  become: true
  become_user: stucco

- name: build collectors
  shell: ./scripts/maven-collectors-build.sh chdir={{ stucco_collector_dir }} creates={{ stucco_collector_dir }}/target/scheduler.jar
  become: true
  become_user: stucco

- name: wait for rmq
  wait_for: port={{ rabbitmq_port }} delay=10

- name: load data
  shell: java -Xmx2G -jar {{ stucco_collector_dir }}/target/collect.jar -load -config {{ stucco_collector_config }} -section {{ stucco_collector_env }} chdir={{ stucco_dir }}
  when: stucco_collector_mode == "once"
  become: true
  become_user: stucco

- name: copy scheduler supervisord config
  template: src=supervisor/stucco-scheduler.conf dest=/etc/supervisor/conf.d/stucco-scheduler.conf
  when: stucco_collector_mode == "daemon"
  become: true
  become_user: root

- name: reload supervisord
  shell: /usr/bin/supervisorctl reload
  when: stucco_collector_mode == "daemon"
  become: true
  become_user: root
