---

- name: create group
  group: name={{ stucco_group }}
- name: create user
  user: name={{ stucco_user }} group={{ stucco_group }} comment="Stucco User"
- name: create Stucco directory
  file: path={{ stucco_dir }} owner={{ stucco_user }} group={{ stucco_group }} state=directory mode=4777

- name: create Stucco bin directory
  file: path={{ stucco_bin }} owner={{ stucco_user }} group={{ stucco_group }} state=directory mode=4777

- name: download ontology repo
  git: repo=https://github.com/stucco/ontology.git dest={{ stucco_dir }}/ontology
- name: download endogenous-data-uc1 repo
  git: repo=https://github.com/stucco/endogenous-data-uc1.git dest={{ stucco_dir }}/endogenous-data-uc1

# CONFIGURATION FOR ETCD
- name: download config repo
  git: repo=https://github.com/stucco/config2.git dest={{ stucco_dir }}/config
- name: make sure etcd is running
  service: name=etcd state=started
- name: setup config
  shell: NODE_ENV={{ stucco_env }} node load.js chdir={{ stucco_dir }}/config/loader

# COLLECTORS
- name: download collectors repo
  git: repo=https://github.com/stucco/collectors.git dest={{ stucco_dir }}/collectors
- name: build collectors
  shell: ./maven-collectors-build.sh > /tmp/collectors-build.out chdir={{ stucco_dir }}/collectors creates={{ stucco_dir }}/target/scheduler.jar

# RT
- name: download rt repo
  git: repo=https://github.com/stucco/rt.git dest={{ stucco_dir }}/rt
- name: copy rt config template (THIS IS TEMPORARY, SHOULD USE CONFD)
  template: src=rt-config.yaml dest={{ stucco_dir }}/rt/config.yaml mode=0644
- name: make sure titan is running
  service: name=titan state=started
- name: build rt
  shell: ./maven-rt-build.sh > /tmp/rt-build.out chdir={{ stucco_dir }}/rt creates={{ stucco_dir }}/rt/streaming-processor/target/rt-structured.jar

# DOCUMENT-SERVICE
- name: create stucco GOPATH directory for document-service
  file: path={{ gopath }}/src/github.com/stucco/document-service owner={{ stucco_user }} group={{ stucco_group }} state=directory mode=4777 recurse=yes
- name: download document-service repo
  git: repo=https://github.com/stucco/document-service.git dest={{ gopath }}/src/github.com/stucco/document-service
- name: test document-service
  shell: "(GOPATH={{ gopath }} {{ goroot }}/bin/go run doc-service.go -port=8000 &) && sleep 2 && GOPATH={{ gopath }} {{ goroot }}/bin/go test chdir={{ gopath }}/src/github.com/stucco/document-service"
- name: build document-service
  shell: "GOPATH={{ gopath }} {{ goroot }}/bin/go build doc-service.go chdir={{ gopath }}/src/github.com/stucco/document-service"
- name: install document-service
  file: src={{ gopath }}/src/github.com/stucco/document-service/doc-service dest={{ stucco_bin }}/doc-service state=link
# - name: update etcd with configuration
#   shell: /usr/local/sbin/etcdctl

# UI
- name: download ui repo
  git: repo=https://github.com/stucco/ui.git dest={{ stucco_dir }}/ui version=polymer-051
- name: prepare ui - install sass gem
  gem: name=sass user_install=no state=present
- name: prepare ui - install compass gem
  gem: name=compass user_install=no state=present
- name: prepare ui - install http-server
  npm: name=http-server global=yes production=yes
- name: prepare ui - install grunt-cli
  npm: name=grunt-cli global=yes production=yes
- name: prepare ui - install node_modules
  npm: path={{ stucco_dir }}/ui
- name: update ui rexster host
  replace: dest={{ stucco_dir }}/ui/app/index.html regexp='(queryHost=)"localhost"' replace='\1"{{ rexster_host }}"' backup=yes
- name: build ui (using a bash shell to make sure ruby gems are available)
  shell: bash -lc "grunt build" chdir={{ stucco_dir }}/ui

# START SERVICES
- name: copy rt supervisord config
  template: src=etc/supervisor/conf.d/stucco-rt.conf dest=/etc/supervisor/conf.d/stucco-rt.conf
- name: copy document-service supervisord config
  template: src=etc/supervisor/conf.d/stucco-doc.conf dest=/etc/supervisor/conf.d/stucco-doc.conf
- name: copy ui supervisord config
  template: src=etc/supervisor/conf.d/stucco-ui.conf dest=/etc/supervisor/conf.d/stucco-ui.conf
- name: reload supervisord
  shell: /usr/bin/supervisorctl reload

- name: set permissions for stucco_dir
  file: path={{ stucco_dir }} state=directory recurse=yes owner={{ stucco_user }} group={{ stucco_group }}