---
- name: install common packages (build-essential, git, mercurial, supervisor, zip, unzip, rsync, curl, wget)
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - build-essential
    - git
    - mercurial
    - supervisor
    - zip
    - unzip
    - rsync
    - curl
    - wget
