---

- file: path={{ install_dir }}
- get_url: url={{ download_url }} dest={{ install_dir }}/confd
- file: path={{ install_dir }}/confd owner=root mode=0755

- file: path={{ config_base_dir }} owner=root mode=0755 recurse=yes state=directory
- template: src=etc/confd/confd.toml dest={{ config_file }} owner=root mode=0644

- file: path={{ conf_dir }} owner=root mode=0755 recurse=yes state=directory
- file: path={{ templates_dir }} owner=root mode=0755 recurse=yes state=directory

- template: src=etc/init/confd.conf dest=/etc/init/confd.conf owner=root mode=0644
  notify: restart confd

- service: name=confd enabled=yes