---
#this supervisord shim is kind of hacky, but it does what it needs to.
- name: copy postgresql db monitor
  template: src=postgresql_monitor.sh dest={{ stucco_dir }}/postgresql_monitor.sh

- name: copy supervisord conf for db monitoring script
  template: src=supervisor/db-monitor.conf dest=/etc/supervisor/conf.d/db-monitor.conf

- name: reload supervisord
  shell: /usr/bin/supervisorctl reload

- name: wait for postgresql
  wait_for: port=5432 delay=10  

- name: create stucco db user
  shell: psql -c "CREATE USER stucco WITH PASSWORD 'stucco' CREATEDB CREATEROLE SUPERUSER REPLICATION;"
  become: true
  become_user: postgres

- name: initialize stucco db user
  shell: createdb
  become: true
  become_user: stucco

- name: create the database as stucco user
  shell: psql -c "CREATE DATABASE testdb;"
  become: true
  become_user: stucco

