---
#this supervisord shim is kind of hacky, but it does what it needs to.
- name: copy postgresql db monitor
  template: src=postgresql_monitor.sh dest={{ stucco_dir }}/postgresql_monitor.sh

- name: copy supervisord conf for db monitoring script
  template: src=supervisor/db-monitor.conf dest=/etc/supervisor/conf.d/db-monitor.conf

- name: reload supervisord
  shell: /usr/bin/supervisorctl reload 

- name: wait for postgresql
  wait_for: port=5432 delay=10

- name: install setfacl support
  become: yes
  apt: pkg=acl

- name: create stucco db user
#  shell: createuser --createdb --createrole --superuser --username=postgres stucco;
  shell: psql -c "CREATE USER {{ postgresql_superuser }} WITH PASSWORD '{{ postgresql_password }}' CREATEDB CREATEROLE SUPERUSER REPLICATION;"
  become: true
  become_user: postgres

- name: create the database as {{ postgresql_superuser }} user
  shell: createdb -O {{ postgresql_superuser }} {{ item.name }}
  become: true
  become_user: postgres
  with_items: "{{ postgresql_databases }}"

- name: initialize stucco user db
  shell: createdb -O {{ postgresql_superuser }} {{ postgresql_superuser }}
  become: true
  become_user: postgres

#- name: create the database as {{ postgresql_superuser }} user
#  shell: createdb -O {{ postgresql_superuser }} {{ item }}
#  #shell: psql -c "CREATE DATABASE {{ item }} OWNER {{ postgresql_superuser }};"
#  become: true
#  become_user: "{{ postgresql_superuser }}"
#  with_items:
#   "{{ postgresql_databases }}"

