---
#this supervisord shim is kind of hacky, but it does what it needs to.
- name: copy postgresql db monitor
  template: src=postgresql_monitor.sh dest={{ stucco_dir }}/postgresql_monitor.sh

- name: copy supervisord conf for db monitoring script
  template: src=supervisor/db-monitor.conf dest=/etc/supervisor/conf.d/db-monitor.conf

- name: reload supervisord
  shell: /usr/bin/supervisorctl reload

- name: wait for postgresql
  wait_for: port=5432 delay=10  