---

#- name: Copy the rexster configuration template
#  template: src=rexster-cassandra-es.xml dest={{ titan_path }}/conf/rexster-cassandra-es.xml

- name: start orientdb service
  command: 'service orientdb start'

#- name: make sure orientdb is running
#  service: name=orientdb state=restarted

- name: download graph-init repo
  git: repo=https://github.com/stucco/graph-init.git version=DBConnection dest={{ stucco_graph_init_dir }}

- name: build schema and index application 
  command: ./schema-build.sh chdir={{ stucco_graph_init_dir }}

- name: wait for orientdb
  wait_for: port=2424 delay=10

- name: create database
  shell: /opt/orientdb-community-2.0.1/bin/console.sh create database remote:localhost:2424/graph root root plocal
#TODO: check version, build path above from that.
#TODO: confirm it does not exist before creating

- name: populate orient with schema and build indexes
  command: ./populate-schema-indexes.sh chdir={{ stucco_graph_init_dir }}
