---
- hosts: all
  sudo: yes
  sudo_user: root
  vars:

    rabbitmq_ssl: false
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_exchange: stucco
    rabbitmq_user: stucco
    rabbitmq_password: stucco
    rabbitmq_conf_tcp_listeners_address: '0.0.0.0'
    rabbitmq_conf_tcp_listeners_port: "{{ rabbitmq_port }}"
    rabbitmq_users_definitions: [{vhost: /, user: "{{ rabbitmq_user }}", password: "{{ rabbitmq_password }}" }]

    stucco_dir: /stucco

    stucco_doc_host: localhost
    stucco_doc_port: 8118

    stucco_ui_host: "{{ host_ip }}"
    stucco_ui_port: 8000

    stucco_collector_env: demo

    postgresql_version: 9.4

    postgresql_listen_addresses:
      - localhost
    postgresql_port: 5432

    postgresql_superuser: stucco
    postgresql_databases:
      - name: testdb

  roles:
  - { role: stucco.common }
  - { role: mikeiannacone.rabbitmq }
  - { role: stucco.graph }
  - { role: stucco.doc }
  - { role: stucco.rt }
  - { role: stucco.ui }
  - { role: stucco.collectors }

  environment:
    STUCCO_DB_TYPE: "POSTGRESQL"
    STUCCO_DB_CONFIG: "/stucco/graph-db-connection-service/graph-db-connection/config/postgresql.yml"
    STUCCO_DB_INDEX_CONFIG: