---
- hosts: all
  sudo: yes
  sudo_user: root
  vars:
    titan_version: 0.5.4

    rabbitmq_ssl: false
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_exchange: stucco
    rabbitmq_user: stucco
    rabbitmq_password: stucco
    rabbitmq_conf_tcp_listeners_address: '0.0.0.0'
    rabbitmq_conf_tcp_listeners_port: "{{ rabbitmq_port }}"
    rabbitmq_users_definitions: [{vhost: /, user: "{{ rabbitmq_user }}", password: "{{ rabbitmq_password }}" }]

    rexster_host: "{{ host_ip }}"
    rexster_http_port: 8182
    rexster_rexpro_port: 8184

    stucco_dir: /stucco

    stucco_doc_host: localhost
    stucco_doc_port: 8118

    stucco_ui_host: "{{ host_ip }}"
    stucco_ui_port: 8000

    stucco_collector_env: demo

  roles:
  - { role: stucco.common }
  - { role: jgoodall.titan }
  - { role: Mayeu.RabbitMQ }
  - { role: stucco.rt }
  - { role: stucco.doc }
  - { role: stucco.ui }
  - { role: stucco.collectors }
