---
- hosts: all
  sudo: yes
  sudo_user: root
  vars:
    rmq_user: stucco
    rmq_password: stucco

  roles:
  - { role: ornl-sava.common }
  - { role: retr0h.etcd, etcd_version: v0.4.6 }
  - { role: ornl-sava.confd }
  # - { role: smola.java, java_packages: [oracle-java7-installer, oracle-java7-set-default] }
  # - { role: ornl-sava.maven, version: 3.1.1 }
  # - { role: ornl-sava.titan }
  # - { role: Mayeu.RabbitMQ, rabbitmq_ssl: false, rabbitmq_conf_tcp_listeners_address: '0.0.0.0', rabbitmq_users_definitions: [{vhost: /, user: "{{ rmq_user }}", password: "{{ rmq_password }}" }] }
  # - { role: Stouts.nodejs }
  # - { role: ornl-sava.stucco, config_env: vagrant, rabbitmq_user: "{{ rmq_user }}", rabbitmq_password: "{{ rmq_password }}" }
