---
- hosts: all
  sudo: yes
  sudo_user: root
  vars:

    rabbitmq_ssl: false
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_exchange: stucco
    rabbitmq_user: stucco
    rabbitmq_password: stucco
    rabbitmq_conf_tcp_listeners_address: '0.0.0.0'
    rabbitmq_conf_tcp_listeners_port: "{{ rabbitmq_port }}"
    rabbitmq_users_definitions: [{vhost: /, user: "{{ rabbitmq_user }}", password: "{{ rabbitmq_password }}" }]

    stucco_dir: /stucco

    stucco_doc_host: localhost
    stucco_doc_port: 8118

    stucco_ui_host: "{{ host_ip }}"
    stucco_ui_port: 8000

    stucco_collector_env: demo

    environment_config:
      STUCCO_DB_TYPE: ORIENTDB
      STUCCO_DB_CONFIG: "/stucco/graph-init/config/orientdb.yml"
      STUCCO_DB_INDEX_CONFIG: "/stucco/graph-init/config/stucco_orientdb_indexing.json"

  roles:
  - { role: franklinkim.environment }
  - { role: stucco.common }
  - { role: Mayeu.RabbitMQ }
  - { role: stucco.graph }
  - { role: stucco.rt }
  - { role: stucco.doc }
  - { role: stucco.ui }
  - { role: stucco.collectors }
