---
- get_url: url={{ maven_url }} dest=/tmp/maven.zip
  register: get_url_result
  until: get_url_result | succeeded
  retries: 5
  delay: 10

- get_url: url={{ maven_url }}.md5 dest=/tmp/maven.md5
  register: get_url_result
  until: get_url_result | succeeded
  retries: 5
  delay: 10

- command: echo " "/tmp/maven.zip >> /tmp/maven.md5 && md5sum -c /tmp/maven.md5

- file: path={{ maven_prefix }} state=directory

- unarchive: >
    copy=no
    src=/tmp/maven.zip
    dest={{ maven_prefix }}

- file: path=/tmp/maven.zip state=absent
- file: path=/tmp/maven.md5 state=absent

- template: src=etc/profile.d/maven.sh dest=/etc/profile.d/maven.sh owner=root group=root mode=0644

- file: src={{ maven_dir }}/bin/mvn dest=/usr/local/bin/mvn owner=root group=root state=link
