---
- name: Download Maven#
  get_url: url={{ maven_url }} dest=/tmp/maven.zip
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 10

# There are some network errors which `wget` handles and `get_url` module does not, so added this check/fallback.
- stat: path=/tmp/maven.zip
  register: maven_file

- shell: wget {{ maven_url }} -O /tmp/maven.zip
  when: maven_file.stat.exists == False

- name: Download Maven checksum
  get_url: url={{ maven_url }}.md5 dest=/tmp/maven.md5
  register: get_url_result
  until: get_url_result | succeeded
  retries: 3
  delay: 10

# There are some network errors which `wget` handles and `get_url` module does not, so added this check/fallback.
- stat: path=/tmp/maven.md5
  register: maven_file_md5

- shell: wget {{ maven_url }}.md5 -O /tmp/maven.md5
  when: maven_file_md5.stat.exists == False

- command: echo " "/tmp/maven.zip >> /tmp/maven.md5 && md5sum -c /tmp/maven.md5

- file: path={{ maven_prefix }} state=directory

- unarchive: >
    copy=no
    src=/tmp/maven.zip
    dest={{ maven_prefix }}

- file: path=/tmp/maven.zip state=absent
- file: path=/tmp/maven.md5 state=absent

- template: src=etc/profile.d/maven.sh dest=/etc/profile.d/maven.sh owner=root group=root mode=0644

- file: src={{ maven_dir }}/bin/mvn dest=/usr/local/bin/mvn owner=root group=root state=link
