---
galaxy_info:
  author: John Goodall
  description: An Ansible role for installing maven 3.
  company: Oak Ridge National Laboratory
  license: Apache
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
dependencies: []
