[template]
src = "scheduler-config.tmpl"
dest = "{{ stucco_dir }}/collectors/config.yaml"
uid = 0
gid = 0
mode = "0644"
keys = [
  "/stucco",
  "/rabbitmq",  
]
reload_cmd = "supervisorctl restart stucco-scheduler"
